# Generated by Django 4.2.23 on 2025-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('academic', 'Academic'), ('selfhelp', 'Self-Help'), ('biography', 'Biography')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
